export const DEFAULT_OPERATIONS_POLICY = {
  enabled: false,
  git_stage_enabled: false,
  git_commit_enabled: false,
  git_branch_enabled: false,
  git_branch_manage_enabled: false,
  git_push_enabled: false,
  github_pull_request_enabled: false,
  github_workflow_dispatch_enabled: false,
  allowed_workflows: [],
  github_merge_enabled: false,
  git_sync_enabled: false,
  script_run_enabled: false,
  allowed_scripts: {},
  codex_task_run_enabled: false,
  codex_task_max_runtime_ms: 1_800_000,
  codex_task_max_output_bytes: 1_048_576,
  codex_task_inherit_env: [],
  claude_ato_001_enabled: false,
  max_paths_per_operation: 50,
  cleanup_enabled: false,
  cleanup_allowed_globs: [
    ".chatgpt/tool-tests/**",
    ".chatgpt/backups/**",
    ".chatgpt/audits/**",
    ".chatgpt/backlog/**",
    ".chatgpt/codex-runs/**",
    "coverage/**",
    "dist/**",
    "test-results/**"
  ]
};
